# Generated by Django 4.2.26 on 2025-11-19 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_compte', models.CharField(choices=[('COURANT', 'Compte Courant'), ('EPARGNE', 'Compte Épargne')], default='COURANT', max_length=20)),
                ('solde', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('numero_compte', models.CharField(max_length=30, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitPret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('taux_ref', models.DecimalField(decimal_places=2, default=3.5, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TypeEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeLogement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('libelle', models.CharField(max_length=100)),
                ('date_execution', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('DEBIT', 'Débit'), ('CREDIT', 'Crédit')], max_length=10)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='scoring.compte')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_naissance', models.DateField(blank=True, null=True)),
                ('ville_naissance', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_souhaite', models.IntegerField()),
                ('duree_souhaitee_annees', models.IntegerField()),
                ('apport_personnel', models.IntegerField(default=0)),
                ('revenus_mensuels', models.IntegerField()),
                ('loyer_actuel', models.IntegerField(default=0)),
                ('dettes_mensuelles', models.IntegerField(default=0)),
                ('enfants_a_charge', models.IntegerField(default=0)),
                ('sante_snapshot', models.CharField(choices=[('BON', 'Bon'), ('MOYEN', 'Moyen'), ('FAIBLE', 'Faible')], default='BON', max_length=10)),
                ('score_calcule', models.IntegerField(blank=True, null=True)),
                ('taux_calcule', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recommendation', models.CharField(blank=True, max_length=50)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En Attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('emploi_snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoring.typeemploi')),
                ('logement_snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoring.typelogement')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoring.produitpret')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_visible', models.CharField(max_length=4)),
                ('date_expiration', models.DateField()),
                ('plafond_paiement', models.IntegerField(default=2000)),
                ('plafond_retrait', models.IntegerField(default=500)),
                ('est_bloquee', models.BooleanField(default=False)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartes', to='scoring.compte')),
            ],
        ),
    ]
