# Generated by Django 4.2.26 on 2025-11-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carte',
            name='paiement_etranger_actif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carte',
            name='sans_contact_actif',
            field=models.BooleanField(default=True),
        ),
    ]
