# Generated by Django 4.2.26 on 2025-11-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_carte_paiement_etranger_actif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
    ]
