# Generated by Django 4.2.25 on 2025-11-19 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoring', '0003_compte_est_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='categorie',
            field=models.CharField(choices=[('ALIM', 'Alimentation & Courses'), ('LOGEMENT', 'Logement & Factures'), ('TRANSPORT', 'Transport'), ('LOISIRS', 'Loisirs & Sorties'), ('SANTE', 'Santé'), ('SHOPPING', 'Shopping'), ('VIREMENT', 'Virement'), ('SALAIRE', 'Salaire & Revenus'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20),
        ),
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('iban', models.CharField(max_length=34)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaires', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
