# Generated by Django 4.2.25 on 2025-11-20 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_transaction_categorie_beneficiaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='type_compte',
            field=models.CharField(choices=[('COURANT', 'Compte Courant'), ('EPARGNE', 'Compte Épargne'), ('PRO', 'Compte Pro / Business')], default='COURANT', max_length=20),
        ),
        migrations.AlterField(
            model_name='demandecredit',
            name='duree_souhaitee_annees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='demandecredit',
            name='emploi_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoring.typeemploi'),
        ),
        migrations.AlterField(
            model_name='demandecredit',
            name='logement_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoring.typelogement'),
        ),
        migrations.AlterField(
            model_name='demandecredit',
            name='montant_souhaite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='demandecredit',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoring.produitpret'),
        ),
        migrations.AlterField(
            model_name='demandecredit',
            name='revenus_mensuels',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='libelle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
