# Generated by Django 4.2.25 on 2025-11-21 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0005_alter_compte_type_compte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilclient',
            name='abonnement',
            field=models.CharField(choices=[('ESSENTIEL', 'Essentiel'), ('PLUS', 'Plus'), ('INFINITE', 'Infinite')], default='ESSENTIEL', max_length=15),
        ),
        migrations.AddField(
            model_name='profilclient',
            name='prochain_abonnement',
            field=models.CharField(blank=True, choices=[('ESSENTIEL', 'Essentiel'), ('PLUS', 'Plus'), ('INFINITE', 'Infinite')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profilclient',
            name='prochaine_facturation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
