# Generated by Django 4.2.25 on 2025-11-21 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoring', '0007_messagesupport'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecredit',
            name='ia_decision',
            field=models.CharField(blank=True, choices=[('EN_ATTENTE', 'En Attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='demandecredit',
            name='mensualite_calculee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
                ('type', models.CharField(choices=[('VIREMENT', 'Virement'), ('TRANSACTION', 'Transaction'), ('CREDIT', 'Crédit'), ('INFO', 'Info')], default='INFO', max_length=20)),
                ('url', models.CharField(blank=True, max_length=250)),
                ('est_lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
