# Generated by Django 4.2.25 on 2025-11-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0009_demandedecouvert'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaire',
            name='surnom',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
