# Generated by Django 4.2.25 on 2025-11-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0010_beneficiaire_surnom'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecredit',
            name='soumise',
            field=models.BooleanField(default=False),
        ),
    ]
