# Generated by Django 4.2.25 on 2025-11-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0011_demandecredit_soumise'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecredit',
            name='dernier_prelevement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandecredit',
            name='echeances_payees',
            field=models.IntegerField(default=0),
        ),
    ]
