# Generated by Django 4.2.25 on 2025-11-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0012_demandecredit_dernier_prelevement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesupport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='support/'),
        ),
        migrations.AddField(
            model_name='messagesupport',
            name='mis_a_jour_le',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
