# Generated by Django 4.2.25 on 2025-11-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0013_messagesupport_image_messagesupport_mis_a_jour_le'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesupport',
            name='a_ete_modifie',
            field=models.BooleanField(default=False),
        ),
    ]
