# Generated by Django 4.2.25 on 2025-12-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0014_messagesupport_a_ete_modifie'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaire',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='iban',
            field=models.CharField(blank=True, max_length=34),
        ),
    ]
