# Generated by Django 4.2.25 on 2025-12-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0015_beneficiaire_telephone_alter_beneficiaire_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='entreprise_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='compte',
            name='entreprise_nom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='compte',
            name='entreprise_siret',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
