# Generated by Django 4.2.25 on 2025-12-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0016_compte_entreprise_contact_compte_entreprise_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='operation_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
