# Generated by Django 4.2.25 on 2025-12-12 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoring', '0017_transaction_operation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirementProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cible_iban', models.CharField(blank=True, max_length=34)),
                ('cible_phone', models.CharField(blank=True, max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif', models.CharField(blank=True, max_length=100)),
                ('prochaine_execution', models.DateField()),
                ('recurrence', models.CharField(choices=[('NONE', 'Unique'), ('MENSUEL', 'Mensuel')], default='NONE', max_length=10)),
                ('actif', models.BooleanField(default=True)),
                ('derniere_execution', models.DateTimeField(blank=True, null=True)),
                ('beneficiaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoring.beneficiaire')),
                ('compte_emetteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virements_programmes', to='scoring.compte')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virements_programmes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prochaine_execution'],
            },
        ),
    ]
