# Generated by Django 4.2.25 on 2025-12-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0018_virementprogramme'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecredit',
            name='date_acceptation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
