# Generated by Django 4.2.25 on 2025-12-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0019_demandecredit_date_acceptation'),
    ]

    operations = [
        migrations.AddField(
            model_name='virementprogramme',
            name='solde_minimum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
