# Generated by Django 4.2.25 on 2025-12-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0020_virementprogramme_solde_minimum'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecredit',
            name='jour_prelevement',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
