# Generated by Django 4.2.25 on 2025-12-12 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0021_demandecredit_jour_prelevement'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecredit',
            name='compte_versement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits_verses', to='scoring.compte'),
        ),
    ]
