# Generated by Django 4.2.25 on 2025-12-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0022_demandecredit_compte_versement'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecredit',
            name='capital_initial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='demandecredit',
            name='capital_restant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='demandecredit',
            name='interets_payes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
