# Generated by Django 4.2.25 on 2025-12-13 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0024_auto_fix_interets_payes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandecredit',
            name='capital_initial',
        ),
        migrations.RemoveField(
            model_name='demandecredit',
            name='capital_restant',
        ),
        migrations.RemoveField(
            model_name='demandecredit',
            name='interets_payes',
        ),
    ]
