# Generated by Django 4.2.25 on 2025-12-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0025_remove_demandecredit_capital_initial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecredit',
            name='diplome',
            field=models.BooleanField(default=True, verbose_name='Diplômé(e) (Bac+)'),
        ),
        migrations.AddField(
            model_name='demandecredit',
            name='marie',
            field=models.BooleanField(default=False, verbose_name='Marié(e)'),
        ),
    ]
